name: user_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  equatable: ^2.0.5
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  uuid: ^4.5.1
dev_dependencies:
  build_runner: ^2.4.13
